export ZSH="YOURHOMEDIR/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"
#ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_MODE='nerdfont-complete'

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon root_indicator host background_jobs dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status)

POWERLEVEL9K_PROMPT_ON_NEWLINE=false
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true

POWERLEVEL9K_HOST_TEMPLATE="%n@%2m"
POWERLEVEL9K_HOST_LOCAL_BACKGROUND="003"
POWERLEVEL9K_HOST_LOCAL_FOREGROUND="236"
POWERLEVEL9K_HOST_REMOTE_BACKGROUND="003"
POWERLEVEL9K_HOST_REMOTE_FOREGROUND="236"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="▶ "
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_ICON_BACKGROUND='236'
POWERLEVEL9K_ICON_FOREGROUND='015'
POWERLEVEL9K_STATUS_VERBOSE=false

source $ZSH/oh-my-zsh.sh
